In [115]:
import pandas as pd

In [117]:
df = pd.DataFrame(
    {'HomeTeam':['A','B','C','D','E','A','B','C','D','E','A','B','C']
     ,'AwayTeam':['C','A','B','E','D','B','D','E','C','A','E','C','A']
     ,'FTHG':[3,2,5,4,2,1,6,2,3,1,2,2,1]
     ,'FTAG':[0,3,6,4,2,0,7,2,4,0,3,4,1]
     , 'FTR' : ['Home','Away','Away','Draw','Draw','Home','Away','Draw','Away','Home','Away','Away','Draw']
    })

In [127]:
df

,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HomeStreak,AwayStreak,HTGS,HTGC,ATGS,ATGC
0,A,C,3,0,Home,----,----,0,0,0,0
1,B,A,2,3,Away,----,W---,0,0,3,0
2,C,B,5,6,Away,L---,L---,0,3,2,3
3,D,E,4,4,Draw,----,----,0,0,0,0
4,E,D,2,2,Draw,D---,D---,4,4,4,4
5,A,B,1,0,Home,WW--,WL--,6,2,8,8
6,B,D,6,7,Away,LWL-,DD--,8,9,6,6
7,C,E,2,2,Draw,LL--,DD--,5,9,6,6
8,D,C,3,4,Away,WDD-,DLL-,13,12,7,11
9,E,A,1,0,Home,DDD-,WWW-,8,8,7,2
10,A,E,2,3,Away,LWWW,WDDD,7,3,9,8
11,B,C,2,4,Away,LLWL,WDLL,14,16,11,14
12,C,A,1,1,Draw,WWDL,LLWW,15,16,9,6

In [119]:
#across all seasons thus far
uniqueTeams = df['HomeTeam'].unique()

#build dict with ALL teams; initialize to ----- for each
teamStreak = {uniqueTeams[i]: {'GS': 0,'GC':0,'Streak':'----'} for i in range(0,len(uniqueTeams))}; 

#setup new column and assign it an initial value
# TGS = Total goals scores, TGC = Total goals conceded
df['HomeStreak'] = 'Not set'
df['AwayStreak'] = 'Not set'
df['HTGS'] = 0
df['HTGC'] = 0
df['ATGS'] = 0
df['ATGC'] = 0

In [123]:
teamStreak

{'A': {'GS': 0, 'GC': 0, 'Streak': '----'},
 'B': {'GS': 0, 'GC': 0, 'Streak': '----'},
 'C': {'GS': 0, 'GC': 0, 'Streak': '----'},
 'D': {'GS': 0, 'GC': 0, 'Streak': '----'},
 'E': {'GS': 0, 'GC': 0, 'Streak': '----'}}

In [125]:
for index,row in df.iterrows():
    
    #Populate streak data into columns before game outcome is counted
    df.at[index,'HomeStreak'] = teamStreak[row['HomeTeam']]['Streak'];
    df.at[index,'AwayStreak'] = teamStreak[row['AwayTeam']]['Streak'];
    df.at[index,'HTGS'] = teamStreak[row['HomeTeam']]['GS'];
    df.at[index,'ATGS'] = teamStreak[row['AwayTeam']]['GS'];
    df.at[index,'HTGC'] = teamStreak[row['HomeTeam']]['GC'];
    df.at[index,'ATGC'] = teamStreak[row['AwayTeam']]['GC'];
    
    teamStreak[row['HomeTeam']]['GS'] += row['FTHG']
    teamStreak[row['AwayTeam']]['GC'] += row['FTHG']
    teamStreak[row['AwayTeam']]['GS'] += row['FTAG']
    teamStreak[row['HomeTeam']]['GC'] += row['FTAG']
    
    #check who won and who lost
    if (row['FTR']=='Draw'):
        teamStreak[row['HomeTeam']]['Streak'] = 'D' + teamStreak[row['HomeTeam']]['Streak']
        teamStreak[row['AwayTeam']]['Streak'] = 'D' + teamStreak[row['AwayTeam']]['Streak']
    elif (row['FTR']=='Home'):
        teamStreak[row['HomeTeam']]['Streak'] = 'W' + teamStreak[row['HomeTeam']]['Streak']
        teamStreak[row['AwayTeam']]['Streak'] = 'L' + teamStreak[row['AwayTeam']]['Streak']
    elif (row['FTR']=='Away'):
        teamStreak[row['HomeTeam']]['Streak'] = 'L' + teamStreak[row['HomeTeam']]['Streak']
        teamStreak[row['AwayTeam']]['Streak'] = 'W' + teamStreak[row['AwayTeam']]['Streak']

    #snipping off last character since above if block added a result to start
    teamStreak[row['HomeTeam']]['Streak'] = teamStreak[row['HomeTeam']]['Streak'][0:-1]
    teamStreak[row['AwayTeam']]['Streak'] = teamStreak[row['AwayTeam']]['Streak'][0:-1]

In [126]:
teamStreak

{'A': {'GS': 10, 'GC': 7, 'Streak': 'DLLW'},
 'B': {'GS': 16, 'GC': 20, 'Streak': 'LLLW'},
 'C': {'GS': 16, 'GC': 17, 'Streak': 'DWWD'},
 'D': {'GS': 16, 'GC': 16, 'Streak': 'LWDD'},
 'E': {'GS': 12, 'GC': 10, 'Streak': 'WWDD'}}